CREATE TYPE "WALLET_TYPE" AS ENUM ('CRED', 'DEB');
CREATE TYPE "CURRENCY" AS ENUM ('IDR', 'USD', 'CNY', 'MYR', 'JPY', 'VND');
CREATE TYPE "STATUS_TYPE" AS ENUM ('PENDING', 'ROLLBACK', 'COMMIT');
CREATE TYPE "TRANSACTION_TYPE" AS ENUM ('TOPUP', 'TRANSFER', 'WITHDRAWAL');


CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    WALLET_TYPE "WALLET_TYPE" DEFAULT 'CRED',
    CURRENCY "CURRENCY" DEFAULT 'VND',
    CREATION_DATE TIMESTAMP,
    VERSION INTEGER DEFAULT 0);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    ACCOUNT_ID uuid REFERENCES ACCOUNT(ACCOUNT_ID),
    STATUS_TYPE "STATUS_TYPE" DEFAULT 'PENDING',
    CREATION_DATE Date,
    AMOUNT NUMERIC,
    TRANSACTION_TYPE "TRANSACTION_TYPE" DEFAULT 'TOPUP',
    SOURCE_NAME VARCHAR(255),
    SOURCE_ID VARCHAR(255),
    DESTINATION_NAME VARCHAR(255),
    DESTINATION_ID VARCHAR(255),
    END_TO_END_ID VARCHAR(255),
    VERSION INTEGER DEFAULT 0
)

CREATE TABLE IF NOT EXISTS HISTORY(
    ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    ACCOUNT_ID uuid REFERENCES ACCOUNT(ACCOUNT_ID),
    TRANSACTIONS uuid REFERENCES TRANSACTIONS(TRANSACTION_ID),
    CREATION_DATE TIMESTAMP,
    AMOUNT DOUBLE,
    TRANSACTION_TYPE "TRANSACTION_TYPE" DEFAULT 'TOPUP',
    SOURCE_NAME VARCHAR(255),
    SOURCE_ID VARCHAR(255),
    DESTINATION_NAME VARCHAR(255),
    DESTINATION_ID VARCHAR(255),
    END_TO_END_ID VARCHAR(255),
    VERSION INTEGER DEFAULT 0
)
