services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  db2:
    image: postgres
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root